# Generated by Django 5.1.6 on 2025-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('IT', 'IT')], max_length=50, null=True),
        ),
    ]
