# Generated by Django 5.1.6 on 2025-04-15 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_interest_user_skill_user_sociallink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(choices=[('AI & ML', 'AI & ML'), ('Competitive Programming', 'Competitive Programming'), ('Open Source', 'Open Source'), ('Cybersecurity', 'Cybersecurity'), ('Cloud Computing', 'Cloud Computing'), ('Software Development', 'Software Development'), ('Data Science', 'Data Science'), ('Blockchain Technology', 'Blockchain Technology'), ('Quantum Computing', 'Quantum Computing'), ('Research & Publications', 'Research & Publications'), ('Technical Blogging', 'Technical Blogging'), ('Mathematical Modeling', 'Mathematical Modeling'), ('Scientific Computing', 'Scientific Computing'), ('IoT', 'IoT'), ('Embedded Systems', 'Embedded Systems'), ('Robotics', 'Robotics'), ('Autonomous Systems', 'Autonomous Systems'), ('Game Development', 'Game Development'), ('3D Modeling', '3D Modeling'), ('Augmented Reality (AR)', 'Augmented Reality (AR)'), ('Virtual Reality (VR)', 'Virtual Reality (VR)'), ('Entrepreneurship', 'Entrepreneurship'), ('Product Management', 'Product Management'), ('Startup Culture', 'Startup Culture'), ('Stock Market & Trading', 'Stock Market & Trading'), ('Business Analytics', 'Business Analytics'), ('Tech Meetups & Hackathons', 'Tech Meetups & Hackathons'), ('Public Speaking', 'Public Speaking'), ('Technical Writing', 'Technical Writing'), ('Ethical Hacking', 'Ethical Hacking'), ('Astronomy & Space Tech', 'Astronomy & Space Tech'), ('Biotechnology & Bioinformatics', 'Biotechnology & Bioinformatics'), ('Sustainable Tech', 'Sustainable Tech')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Go', 'Go'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('HTML & CSS', 'HTML & CSS'), ('React.js', 'React.js'), ('Vue.js', 'Vue.js'), ('Angular', 'Angular'), ('Node.js', 'Node.js'), ('Django', 'Django'), ('Flask', 'Flask'), ('Spring Boot', 'Spring Boot'), ('FastAPI', 'FastAPI'), ('Android Development', 'Android Development'), ('iOS Development', 'iOS Development'), ('Flutter', 'Flutter'), ('React Native', 'React Native'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Natural Language Processing (NLP)', 'Natural Language Processing (NLP)'), ('Computer Vision', 'Computer Vision'), ('Data Science', 'Data Science'), ('Big Data', 'Big Data'), ('Data Visualization', 'Data Visualization'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('Scikit-learn', 'Scikit-learn'), ('Pandas & NumPy', 'Pandas & NumPy'), ('Cybersecurity', 'Cybersecurity'), ('Ethical Hacking', 'Ethical Hacking'), ('Network Security', 'Network Security'), ('Cryptography', 'Cryptography'), ('Penetration Testing', 'Penetration Testing'), ('Blockchain Security', 'Blockchain Security'), ('Web Security', 'Web Security'), ('Cloud Security', 'Cloud Security'), ('Digital Forensics', 'Digital Forensics'), ('Cloud Computing', 'Cloud Computing'), ('AWS', 'AWS'), ('Google Cloud Platform (GCP)', 'Google Cloud Platform (GCP)'), ('Microsoft Azure', 'Microsoft Azure'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('CI/CD Pipelines', 'CI/CD Pipelines'), ('Software Development', 'Software Development'), ('Software Architecture', 'Software Architecture'), ('System Design', 'System Design'), ('Microservices', 'Microservices'), ('API Development', 'API Development'), ('Full Stack Development', 'Full Stack Development'), ('IoT', 'IoT'), ('Embedded Systems', 'Embedded Systems'), ('Arduino', 'Arduino'), ('Raspberry Pi', 'Raspberry Pi'), ('SQL', 'SQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB'), ('MySQL', 'MySQL'), ('Firebase', 'Firebase'), ('Redis', 'Redis'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Robotics', 'Robotics'), ('Autonomous Systems', 'Autonomous Systems'), ('Reinforcement Learning', 'Reinforcement Learning'), ('Project Management', 'Project Management'), ('Agile & Scrum', 'Agile & Scrum'), ('Technical Writing', 'Technical Writing'), ('Product Management', 'Product Management'), ('Business Analytics', 'Business Analytics'), ('Game Development', 'Game Development'), ('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine'), ('Quantum Computing', 'Quantum Computing')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
