# Generated by Django 5.1.6 on 2025-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
