# Generated by Django 5.1.6 on 2025-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_project_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='marks',
            field=models.JSONField(null=True),
        ),
    ]
