# Generated by Django 5.1.6 on 2025-03-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_project_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guide_approval_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
