# Generated by Django 5.1.6 on 2025-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_project_guide_approval_form_alter_course_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='marks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
