# Generated by Django 5.1.6 on 2025-03-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0006_alter_project_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PojectCOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_app.courseoutcome')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projects_app.project')),
            ],
        ),
    ]
