# Generated by Django 5.1.6 on 2025-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0007_courseoutcome_pojectcos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CO_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
