# Generated by Django 5.1.6 on 2025-03-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0008_course_co_finalized'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PojectCOs',
            new_name='ProjectCOs',
        ),
    ]
